using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class SelectedResourceModel
{
    [RealtimeProperty(1, true, true)]
    private string _selectedResource;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SelectedResourceModel : RealtimeModel {
    public string selectedResource {
        get {
            return _selectedResourceProperty.value;
        }
        set {
            if (_selectedResourceProperty.value == value) return;
            _selectedResourceProperty.value = value;
            InvalidateReliableLength();
            FireSelectedResourceDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(SelectedResourceModel model, T value);
    public event PropertyChangedHandler<string> selectedResourceDidChange;
    
    public enum PropertyID : uint {
        SelectedResource = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _selectedResourceProperty;
    
    #endregion
    
    public SelectedResourceModel() : base(null) {
        _selectedResourceProperty = new ReliableProperty<string>(1, _selectedResource);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _selectedResourceProperty.UnsubscribeCallback();
    }
    
    private void FireSelectedResourceDidChange(string value) {
        try {
            selectedResourceDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _selectedResourceProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _selectedResourceProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.SelectedResource: {
                    changed = _selectedResourceProperty.Read(stream, context);
                    if (changed) FireSelectedResourceDidChange(selectedResource);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _selectedResource = selectedResource;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
